### ISSUE TITLE
Unable to get it working on battery

### ISSUE THREAD

**Issue by peturdainn** [Xinyuan-LilyGO/ESP32_S2#3]
Attached LiPo battery, I can measure 3.9V on the BAT and 3.3V on VDD3V3 but on V3V I measure 1.2V. Board doesn't work, no blue led.

When USB-C is plugged in the V3V pin measures 3.29V and the board works, blue led on.

Is there an external condition (connection/...) required to make this work? Or is the board faulty?

**Comment by LilyGO** [comment]
The microcontroller should have a pin for turning on the V3V power supply. This pin needs to be output high.

**Comment by peturdainn** [comment]
Ah, GPIO14 if I read the schematic correctly. Will try tonight.
Thanks

**Comment by peturdainn** [comment]
Confirming that this works!
LILYGO TTGO T8 ESP32-S2 V1.1 needs GPIO14 high for battery operation
